package finalProject;

import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

//import golfApp.HSGolfLogin;
//import golfApp.User;
//import golfApp.UserList;

public class JFrameGUI extends javax.swing.JFrame {

	private static final long serialVersionUID = 7323709150920190108L;
	private javax.swing.JButton loginBtn;
	private javax.swing.JLabel loginMessageLbl;
	private javax.swing.JPanel loginPanel;
	private javax.swing.JLabel mainTitleLbl;
	private javax.swing.JLabel passwordLbl;
	private javax.swing.JPasswordField passwordTxtFld;
	private javax.swing.JLabel userNameLbl;
	private javax.swing.JTextField userNameTxtFld;
	private Scanner userInfo = new Scanner("");
	private static final int WIDTH = 1280;
	private static final int HEIGHT = 720;

	// private UserList users;
	private ArrayList<User> userList;

	/**
	 * Creates new form JFrameGUI
	 */
	public JFrameGUI() throws FileNotFoundException {
		initComponents();
		userList = new ArrayList<User>();
		Scanner readUsers = new Scanner(new File("src/finalProject/users.dat"));
		while (readUsers.hasNext()) {
			String str = readUsers.nextLine();
			userInfo = new Scanner(str);
			System.out.println(str);
			if (userInfo.hasNext()) {
				User newUser = new User(userInfo.next(), userInfo.next());
				userList.add(newUser);
			}
		}
		readUsers.close();

		// users = new UserList();
		// userList = users.getUsers();
		loginMessageLbl.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// @SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		loginPanel = new javax.swing.JPanel();
		mainTitleLbl = new javax.swing.JLabel();
		userNameLbl = new javax.swing.JLabel();
		userNameTxtFld = new javax.swing.JTextField();
		passwordLbl = new javax.swing.JLabel();
		passwordTxtFld = new javax.swing.JPasswordField();
		loginBtn = new javax.swing.JButton();
		loginMessageLbl = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		loginPanel.setBackground(new java.awt.Color(27, 20, 100));
		
		mainTitleLbl.setForeground(Color.WHITE);
		mainTitleLbl.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
		mainTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		mainTitleLbl.setText("FRC 3128 Database Login");
		mainTitleLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

		userNameLbl.setForeground(Color.WHITE);
		userNameLbl.setBackground(new java.awt.Color(27, 20, 100));
		userNameLbl.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
		userNameLbl.setText("Username");

		userNameTxtFld.setCaretColor(new java.awt.Color(0,104,165));
		userNameTxtFld.setForeground(Color.WHITE);
		userNameTxtFld.setFont(new java.awt.Font("Open Sans", 0, userNameTxtFld.getFont().getSize()));
		userNameTxtFld.setBackground(new java.awt.Color(7, 38, 130));

		passwordLbl.setForeground(Color.WHITE);
		passwordLbl.setBackground(new java.awt.Color(27, 20, 100));
		passwordLbl.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
		passwordLbl.setText("Password");

		passwordTxtFld.setCaretColor(new java.awt.Color(0,104,165));
		passwordTxtFld.setEchoChar('•');
		passwordTxtFld.setForeground(Color.WHITE);
		passwordTxtFld.setFont(new java.awt.Font("Tahoma", 0, passwordTxtFld.getFont().getSize()));
		passwordTxtFld.setBackground(new java.awt.Color(7, 38, 130));

		loginBtn.setForeground(Color.WHITE);
		loginBtn.setBackground(new java.awt.Color(27, 20, 100));
		loginBtn.setText("Log In");
		loginBtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loginBtnActionPerformed(evt);
			}
		});

		loginMessageLbl.setFont(new java.awt.Font("Open Sans", 0, loginMessageLbl.getFont().getSize()));
		loginMessageLbl.setForeground(Color.WHITE);
		loginMessageLbl.setText("");

		javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
		loginPanel.setLayout(loginPanelLayout);
		loginPanelLayout.setHorizontalGroup(loginPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(loginPanelLayout.createSequentialGroup().addContainerGap().addGroup(loginPanelLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(loginPanelLayout.createSequentialGroup()
								.addComponent(mainTitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, WIDTH-40,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
								.addGap(0, 0, Short.MAX_VALUE)
								.addGroup(loginPanelLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												loginPanelLayout.createSequentialGroup().addGroup(loginPanelLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(loginPanelLayout.createSequentialGroup()
																.addComponent(passwordLbl)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(passwordTxtFld,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 700,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(loginPanelLayout.createSequentialGroup()
																.addComponent(userNameLbl)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(userNameTxtFld,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 700,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(loginPanelLayout.createSequentialGroup()
																.addGap(34, 34, 34).addComponent(loginBtn)))
														.addGap(172, 172, 172))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												loginPanelLayout.createSequentialGroup().addComponent(loginMessageLbl)
														.addGap(134, 134, 500)))))));
		loginPanelLayout.setVerticalGroup(loginPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(loginPanelLayout.createSequentialGroup().addComponent(mainTitleLbl).addGap(18, 50, 500)
						.addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(userNameLbl).addComponent(userNameTxtFld,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(passwordLbl).addComponent(passwordTxtFld,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(loginBtn).addGap(18, 30, 100).addComponent(loginMessageLbl)
						.addGap(0, 500, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		setSize(WIDTH,HEIGHT);
		//pack();
	}// </editor-fold>//GEN-END:initComponents
	
	private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginBtnActionPerformed
		// TODO add your handling code here:
		
		for (User u : userList) {
			if (u.getUserName().equals(userNameTxtFld.getText()) && u.getPassword().equals(new String(passwordTxtFld.getPassword()))) {
				loginMessageLbl.setText("Welcome " + u.getUserName() + "! Please wait a moment while we log you in...");
				loginMessageLbl.setVisible(true);
				
				Timer timer = new Timer();

				timer.schedule(new TimerTask() {

					@Override
					public void run() {
						dispose();
						try {
							new JFrameHomeScreen().setVisible(true);
						} catch (FileNotFoundException e) {
							System.out.println("BRUH BIG FileNotFoundException");
							e.printStackTrace();
						}
					}
					
				}, 1000);
				
				break;
			} else {
				System.out.println("NOTICE: loginBtnActionPerformed!");
				loginMessageLbl.setText("Invalid username or password");
				loginMessageLbl.setVisible(true);
				super.repaint();
			}
		}
		
		
		
		

	}// GEN-LAST:event_loginBtnActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
//	public static void main(String args[]) {
//		/* Set the Nimbus look and feel */
//		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
//		// (optional) ">
//		/*
//		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
//		 * look and feel. For details see
//		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//		 */
//		try {
//			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger(JFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		}
//		// </editor-fold>
//		// </editor-fold>
//
//		/* Create and display the form */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				try {
//					new JFrameGUI().setVisible(true);
//				} catch (FileNotFoundException ex) {
//					Logger.getLogger(JFrameGUI.class.getName()).log(Level.SEVERE, null, ex);
//				}
//			}
//		});
//	}
}
